#!/usr/bin/python3
def factorize(number):
    factors = []
    for i in range(2, number + 1):
        while number % i == 0:
            factors.append(i)
            number //= i
        if number == 1:
            break
    return factors

def main(input_file):
    with open(input_file, 'r') as file:
        numbers = file.read().splitlines()

    for number_str in numbers:
        number = int(number_str)
        factors = factorize(number)
        if len(factors) < 2:
            continue
        print(f"{number}={factors[0]}*{factors[1]}")

if __name__ == "__main__":
    input_file = "tests/test00"
    main(input_file)
