#!/usr/bin/env bash

check_factor() {
    local num1=$1
    local num2=$2

    if ((num1 < num2)); then
        local temp=$num1
        num1=$num2
        num2=$temp
    fi

    echo "$num1=$num2*$((num1 / num2))"
}

if [ $# -ne 1 ]; then
    echo 'Usage: factors <file>'
    exit 1
else
    while read -r num; do
        check_factor "$num" "$(factor "$num" | awk '{print $2}')"
    done < "$1"
fi
