#!/usr/bin/env bash

# Function to check if a number is prime
is_prime() {
    local num=$1
    if ((num < 2)); then
        return 1
    fi

    for ((i = 2; i <= num / 2; i++)); do
        if ((num % i == 0)); then
            return 1
        fi
    done

    return 0
}

# Function to factorize the RSA number into two prime numbers
factor_rsa() {
    local n=$1
    local p=2
    while true; do
        if ((n % p == 0)); then
            local q=$((n / p))
            if is_prime "$q"; then
                echo "$n=$p*$q"
                return
            fi
        fi
        p=$((p + 1))
    done
}

# Check if the correct number of command line arguments is provided
if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
else
    # Read RSA numbers from the input file
    while read -r num; do
        factor_rsa "$num"
    done < "$1"  # Read from the input file specified on the command line
fi
