#!/usr/bin/env bash

factor_rsa() {
    local n="$1"
    local factors="$(factor "$n")"
    local p q

    IFS=" :" read -r _ p _ q _ <<< "$factors"

    # Make sure p is the smaller prime factor
    if ((p > q)); then
        local tmp="$p"
        p="$q"
        q="$tmp"
    fi

    echo "$n=$p*$q"
}

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
else
    while read -r num; do
        factor_rsa "$num"
    done < "$1"
fi